### PR TITLE
support for xcode 8 beta 5 with swift3

### PR DESCRIPTION
**Pull request by JackieQi**
@wangshengjia 
I created this PR just for you to take a look. Two things to mention:
1. For test dependency (Quick, Nimble), i pointed to my fork to get it compiled. But i didn't fix syntax in test target
2. There are exceptions raised when i push twitter and details page demo. 
from this function lg_setupCustomStyle which i haven't looked into. 

Thanks and can't wait to get this more mature to use it. Keep up.

### CODE REVIEW

**Comment by wangshengjia** [comment]
Thanks a lot for the PR. 👍  
I'll look into the details a little bit later.

**Comment by JackieQi** [comment]
@wangshengjia I just updated unit test. All tests passed successfully except ConvertibleSpec which is caused by .numberOfLines(10) in ConvertibleSpec.swift. which also triggers compiler error. Please take a look.

**Comment by wangshengjia** [comment]
@JackieQi Thanks a lot for your help, this is really cool. I've tested with Xcode 8 beta 6, it works like a charm. 👍 💯 

We'll merge it once it's all stable. Furthermore, we also need to refactor/break some APIs to make them adapt better the Swift 3 best practices.

ps: By the way, just for the information (no big deal at all), the commit 38e1d13 is just too huge for review, tones of code changed by Xcode and by Cocoapods in one single commit. Usually we prefer to separate commits into small units with the unique purpose. It makes code review a lot easier :)

**Comment by JackieQi** [comment]
@wangshengjia Sorry about that. I realized it. I was just trying to get it done.  So the demos still crashed because of lg_setupCustomStyle function not called in UIView extension which i am not sure why.

**Comment by wangshengjia** [comment]
@JackieQi There is nothing to apologize ;-)

I'll take care of this issue a little bit later when I got time, thanks a lot.

**Comment by JackieQi** [comment]
👍

**Pull request merged**
